version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      API_PORT: 4000
      API_HOST: 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./generated-sites:/app/generated-sites
      - ./apps/api/storage:/app/apps/api/storage
      - ./apps/api/uploads:/app/apps/api/uploads
      - ./apps/api/generated:/app/apps/api/generated

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000
    depends_on:
      - api
    ports:
      - "3000:3000"
